sudo: required
dist: trusty

language: go

go:
  - 1.6
  - 1.7
  - tip

os:
  - linux
  - osx

addons:
  apt:
    packages:
      - libxxf86vm-dev
      - libnotify-dev
      - libgtk2.0-dev
      - libpango1.0-dev
      - libatk1.0-dev
      
      
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then free -m; fi

install:
  - gcc --version
  - g++ --version
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ld --version; fi
  - travis_wait 30 go get -t -v -x ./...
  
