sudo: required

language: go

go:
  - 1.6
  - 1.7
  - tip

os:
  - linux
  - osx
    
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5

env: COMPILER=g++-5
      
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi

    
script:
  - ${CC} --version ; ${CXX} --version ; ${GCOV} --version
  - go get -t -v -x ./...
