sudo: required

language: go

go:
  - 1.6
  - 1.7
  - tip

os:
  - linux
#  - osx

cache:
  directories:
    - $HOME/binutils

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5
      - libxxf86vm-dev
      - libnotify-dev
#      - binutils
      
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo unlink /usr/bin/g++ && sudo ln -s /usr/bin/g++-5 /usr/bin/g++; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ld --version; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then free -m; fi
  - gcc --version
  - g++ --version
  - if [ ! -d "$HOME/binutils/bin" ]; then
       wget http://ftp.gnu.org/gnu/binutils/binutils-2.27.tar.bz2 -O - | tar -jxf -;
       cd binutils-2.27;
       ./configure --prefix=${HOME}/binutils;
       make -j 2;
       make install;
    fi
  - export PATH=${HOME}/binutils/bin:$PATH
  
