sudo: required
dist: trusty

language: go

go:
  - 1.7
  - 1.8
  - 1.9
  - tip

os:
  - linux
  - osx

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5
      - libxxf86vm-dev
      - libnotify-dev
      - libgtk-3-dev
      - libpango1.0-dev
      - libatk1.0-dev
      - libglib2.0-dev
      - libglib2.0-0
      - libglu1-mesa-dev
      - libjpeg-dev
      - libtiff-dev
      - libgstreamer1.0-dev
      - libgstreamer-plugins-base1.0-dev
      - libwebkitgtk-3.0-dev
      
before_install:
  - rvm install 2.2.6
  - gem install dropbox-deployment

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then free -m; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 90; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90; fi

script:
  - gcc --version
  - g++ --version
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ld --version; fi
  - travis_wait 50 go get -t -v -x ./...
  - cd utils
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then travis_wait 50 bash build_binary_package.sh linux amd64; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then travis_wait 50 bash build_binary_package.sh darwin amd64; fi

after_success:
  - echo "deploy:" > dropbox-deployment.yml
  - echo "  dropbox_path:\ /Builds" >> dropbox-deployment.yml
  - echo "  artifacts_path:\ \*.zip" >> dropbox-deployment.yml
  - echo "  debug:\ true" >> dropbox-deployment.yml
  - pwd
  - ls
  - dropbox-deployment
#  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then dropbox-deployment; fi
